### ISSUE TITLE
Refactor CMakeLists.txt files

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1202]
@ghorn and I want to refactor the CMake file to be able to better understand what's going on and to be able to maintain the package.

Prerequisites:
 - [x] Refactor SWIG, instead of one interface file including all files, there should a set of .i files in the same directory as the header file, cf. #1203. This should make the `swig/CMakeLists.txt` much simpler.

Subtasks:
 - [x] Resolve cmake warnings #1152 
 - [x] Return ability to compile CasADi C++ without SWIG, #1121 
 - [ ] ~~Get back `python` target, cf. #1119~~
 - [x] Remove the unnecessary installation of header files:
```
install(DIRECTORY ./
  DESTINATION include/casadi/solvers
  FILES_MATCHING PATTERN "*.hpp"
  PATTERN ".svn" EXCLUDE)
```

**Comment by jaeandersson** [comment]
Updated installation instructions, closing issue.
