### ISSUE TITLE
Refactor codegen

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1406]
This issue summarizes the work on the codegen for milestone 2.4:
 - [x] Cost-correct handling of array constants: They are now `double[]`, `int[]`, should be `const double[]`, `const int[]`
 - [x] Use `real_t` define for floating point type (instead of `d`) #610 
 - [x] Default `nn_sparsity` entry point: If undefined, assume all inputs and ouput scalar
 - [x] Default `nn_work` entry point: If undefined, no work needed
 - [x] Statical linking without conflicting symbols, #608
 - [x] Codegen ExternalFunction, #1402
 - [x] Default entry point for generated code #1404
 - [x] Work vectors instead of memory allocation in generated code #1356
 - [x] Command line interface #1398
 - [x] Mex wrapper #1365 
 - [x] Codegen io names #1396 
 - [x] c++ guards #1359 
 - [x] Assertion node #921 
 - [x] Verbose option to codegen (default off)
 - [x] More efficient handling of scalars in MXFunction #1409
 - [x] Generated code should be human-readable #1410
 - [x] Switches #1413
 - [x] Input/output buffers as work vectors #1425
 - [x] Function signature for scalar expressions #1432

For future milestones:
 - Codegen derivative information #1394
 - Codegen sparsity pattern propagation #1393
 - Codegen for NewtonImplicitSolver #676
 - Unittest code generation #1052
 - Graceful failure for multiple defined symbols, #1405
 - Inline functions #1411
 - ~~User-defined binary operations in MX~~ #1412
 - User data in external function interface #1417
