### ISSUE TITLE
Syntax cleanup for version 3.0

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1586]
Continuing the tradition of breaking user's code, this issue serves to collect syntax changes for the 3.0 milestone. This is a continuation of #1300.

Proposed changes:
 - [x] Remove the public classes inheriting from `Function`, cf. #1585
 - [x] Underscore naming convention for function names #1602
 - [ ] ~~Strict naming convention for function objects~~ #1588
 - [x] `Matrix::size` instead of `Matrix::shape` in C++ (conforming with MATLAB)
 - [x] New syntax for "expand" #1589
 - [x] Remove iterators for matrix type (not implemented anyway)
 - [ ] ~~Hide enums from SWIG (note: enums are not type-safe in SWIG - they are simply integers. A string is safer and more user friendly.~~
 - [x] Uniform way for creating solver instances #1590
 - [x] Avoid long function names #1623
 - [x] Remove IO scheme helpers #1624
 - [x] Rename `inner_prod` -> `dot`
 - [x] Rename `DMatrix` -> `DM`, `IMatrix` -> `IM`
 - [x] Rename `mul` -> `mtimes`
 - [x] Rename `jmtimes` -> `jtimes`
