### ISSUE TITLE
Refactor codegen, part 2

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1610]
EDIT (@jaeandersson): Made this a grouping ticket for collecting codegen changes for 2.5

Follow-up of #1406:

- [ ] CodeGenerator::generate and Function::generate name sanitization discards path information #1609
- [ ] Codegenerator should produce the same code if you generate a string or write a file #1605
- [x] ~~Add codegen function which allocates the work vector for you~~ #1606
- [x] Codegen generate_main seems to be broken #1607
- [x] Codegen derivative information #1394
- [ ] Codegen sparsity pattern propagation #1393
- [ ] Codegen for NewtonImplicitSolver #676
- [ ] Unittest code generation #1052
- [ ] Graceful failure for multiple defined symbols, #1405
- [ ] Inline functions #1411
- [x] ~~User data in external function interface~~ #1417
- [x] IO scheme meta information in generate code #1634

**Comment by jaeandersson** [comment]
This issue makes little sense. Refer to the individual issues.
