### ISSUE TITLE
MATLAB front-end

### ISSUE THREAD

**Issue by casadibot** [casadi/casadi#176]
To implement a MATLAB front-end to CasADi, the best alternative is undoubtedly to add/use a MATLAB backend to SWIG. It's a lot of work, but should be manageable if deemed important enough.

Subtasks:
 - [x] Add a MATLAB backend to SWIG that is general enough to generate code for some important user class, e.g. `MX`. Implemented in a [fork of SWIG repo](https://github.com/jaeandersson/swig).
 - [x] Add support for MATLAB generation in the CasADi build system
 - [x] Complete the SWIG backend until it supports all features required by CasADi
 - [x] Add MATLAB-CasADi typemaps cf. also #1304.
 - [x] Get submatrix access and assignment to work
 - [ ] ~~Write unit tests~~ Deferred to #1305
 - [x] Debug the module until all major features either work or gives a recoverable and informative error
 - [ ] ~~Write documentation~~ Deferred to #1306
 - [ ] ~~Fix addition, multiplication etc. from the left (e.g. `3 + SX(2)`), cf. https://github.com/jaeandersson/swig/issues/10~~ Deferred to #1308.
 - [x] Fix horzcat/vertcat/mtimes: `a = [1,2,3]` does not work after `import casadi.*`, cf. #1285

Some minor issues encountered:
 - [x] `ans` output not produced, cf. mail to swig-devel
 - [ ] ~~No docstring produced for classes~~ Deferred to #1306
 - [x] Operator overloading of `&`, `|` and `~` (`and`, `or` and  `not` in MATLAB) is not working, cf. mail to swig-devel.
 - [ ] ~~Auto-completion does not appear to work for generated classes. MATLAB issue?~~ Deferred to #1307.
 - [x] It should be `import casadi.*`, not `import casadi_core.*`

**Comment by jaeandersson** [comment]
Spun https://github.com/casadi/casadi/issues/1304.

**Comment by jaeandersson** [comment]
Spun https://github.com/casadi/casadi/issues/1305.

**Comment by jaeandersson** [comment]
Spun #1306.

**Comment by jaeandersson** [comment]
Spun #1307.

**Comment by jaeandersson** [comment]
Spun #1308.

**Comment by jaeandersson** [comment]
Spun #1309.

**Comment by jaeandersson** [comment]
This issue has now served it's purpose and I'll close it at this point. The MATLAB interface is now essentially feature complete and is ready to be tested, keeping in mind that it is still not stable, nor well documented. Remaining issue has been deferred to dedicated issues.
