### ISSUE TITLE
Refactor AD

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2018]
Refactor AD for speed, maintainability and new functionalities such as Jacobians by finite differencing:
 - [ ] ~~Refactor Jacobian AD algorithm~~ #1055 
 - [x] Refactor Jacobian signature #2011
 - [ ] ~~Allow nondifferentiated inputs and outputs~~ #2013 
 - [x] Add support for numerical differentiation #1026
 - [x] Generic output instructions in MX VM #1382
 - [x] Make nondifferentiated outputs optional for derivative functions #2019
