### ISSUE TITLE
To do 3.6

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2880]
TO DOs for 3.6:
 - [x] Re-enable Ipopt Callbacks
 - [x] Populate change list: Add closed issues, new features [JA + JG]
 - [ ] #3060
 - [x] Build + publish documentation [JG + JA] (hint: pip install -r requirements.txt)
 - [x] Reactivate docstrings for inline documentation [JG]
 - [x] Go through open issues with milestones (3.5, 3.6): postpone or close [JA + JG]
 - [x] test release-3.5.6, see if tests pass [JA]
 - [x] Ensure master not ahead of develop [JG]
 - [x] Sync branches with develop  (git branch --sort=committerdate) [JG]
 - [ ] ~Remove deprecated features~ [JA]
 - [x] Go through clang warnings [JA]
 - [x] Test serialization regression in develop [JG] #3010 
 - [x] Decide future of clang binaries
 - [x] Binaries for commercial plugins [JG]
 - [x] Binaries for M1 [JG]
 - [x] Binaries for MATLAB [JG]
 - [x] Binaries for Octave [JG]
 - [x] Bump minimum CMake version to 3.10 #2884
 - [x] avoid empty vertcat from becoming Sparsity #2549
 - [ ] #3058
 - [x] Re-enable run_slow
 - [x] Regenerate casadi/osqp ".lib" named import library (previously using dlltool) [JG]
 - [x] Run documentation ids generator
 - [ ] #3059
 - [x] Re-add examples to test suite
 Removed:
 - Binaries for aarch64 [JG] ->removed
 - Binaries with clang
 - Prerelease

**Comment by jgillis** [comment]
See also #2807
