### ISSUE TITLE
New integrator overhaul

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#794]
This is a new iteration (after #397) on the way AD is performed on integrator objects. This is necessary to enable support for multiple-shooting and (fast) high-order sensitivity analysis.

Prerequisites:
- [x] Drop support for AD by OO, #884 

Subtasks:
- [x] Generalize generation of augmented DAE, #935 #936
- [x] More efficient sparsity propagation through integrator objects, #934 
- [x] Access to algebraic variables, #504 
- [ ] ~~Solution statistics, #344~~
- [ ] ~~Solution interpolation for fixed-step integrators, #245 #539~~
- [ ] ~~Exploit sensitivity analysis structure in SUNDIALS integrators, #940~~
- [ ] ~~Exploit Jacobian structure in augmented DAEs, #941~~ 
- [x] Make sure that integrators work properly together with parallelization, #531 
- [ ] ~~Preconditioning bug in CVodes, #815~~
- [ ] ~~IDAS quadrature performance issue, #553~~ 
- [ ] ~~Quadrature error control in SUNDIALS on by default, #546~~ 
- [ ] ~~Avoid calculating the Jacobian in SUNDIALS when not needed, #541~~
- [x] Errors in CVodes backward Jacobian, #540 
- [x] Refactor explicit Runge-Kutta integrators, #511 
- [x] Refactor collocation integrators, #948 

Cf. also #929.

Possible follow-ups: #945, #946, #947.

**NOTE: Strikethrough tickets have been moved to #974.**
