### ISSUE TITLE
Another integrator overhaul

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#974]
This is a third iteration on the integrators in CasADi, after #397 and #794.

The iteration is mainly performance oriented. The current implementation should be correct (except for #973), but potentially inefficient for handling large-scale DAEs.

The implementation will start after #554 has been implemented and released.

Subtasks:
- [ ] Sensitivity equations for time-dependent DAEs, #973
- [x] Solution statistics, #344 
- [ ] ~~Solution interpolation for fixed-step integrators #245 #539~~ 
- [x] Exploit sensitivity analysis structure in SUNDIALS integrators, #940
- [ ] Exploit sensitivity analysis structure in collocation integrator #1791
- [x] Exploit Jacobian structure in augmented DAEs, #941 
- [ ] Preconditioning bug in CVodes, #815
- [ ] ~~IDAS quadrature performance issue, #553~~
- [ ] ~~Quadrature error control in SUNDIALS on by default, #546~~
- [ ] ~~Avoid calculating the Jacobian in SUNDIALS when not needed, #541~~
- [x] Remove ControlSimulator #1591
- [x] Merge Simulator and Integrator, #1592
- [x] Deprecate explicitRK(...) and implicitRK(...) #954 
- [x] Upgrade to SUNDIALS 2.6 #1375
- [x] Integrator cannot handle sparse zeros in right-hand-side #1386 
- [x] JIT is not supported in integrator() #1748
- [ ] Collocation integrator does not return algebraic variable at end time #1127
- [ ] Wrong "zf" output for when using collocation-integrator for a DAE #1472
- [x] Make CSparse the default linear solver in the SUNDIALS interface #1783
- [x] Make user_defined linear solver default in the SUNDIALS interface #1785

For future issues:
- Support for root-finding functions to avoid integrating past discontinuities
- Code generation for RKIntegrator #945
- Multiple explicit Runge-Kutta methods #946
- Implement discretize-then-differentiate derivative calculation for RKBase #947
- Jacobian sparsity of explicit 'rk' integrator can be improved #1154

**Comment by pstjohn** [comment]
I would add a thumbs up for root-finding... It's already in sundials and you'd likely be one of the few (only?) packages in python to support event detection in ODE integration.

Is this already implemented? I see some indications you might have in `casadi-sundials/cvodes/cvodes_io.c`, but from this issue I wasn't sure. (Is there a good example to follow if it is implemented?)

Thanks!

**Comment by jaeandersson** [comment]
> I would add a thumbs up for root-finding.

This is off-topic for this issue, but to answer your question, we don't have root-finding or active plans to implement it. It's a tricky thing to get right and I doubt that either me or Joris would look at this unless it's something we need for some project. My preferred way would be to have the rootfinding functions be automatically constructed from the ODE right-hand-side expressions, i.e. analyze which subexpressions are non-differentiable / discountinuous.
